group: game                 # 服务所属的组

tcp:
    addr: 0.0.0.0:10000
    noDelay: false          # 延迟发送
    rTimeout: 10s           # 读超时
    sTimeout: 5s            # 写超时
    sBufferSize: 10         # 发包通道缓冲区大小

kcp:
    addr: 0.0.0.0:20000
    dataShards: 1           # 发包分片数
    parityShards: 0         # 冗余分片数
    noDelay:
        interval: 10ms      # 协议内部工作的 interval，比如 10ms或者 20ms
        resend: 2           # 快速重传模式，默认0关闭（设置为x, x次ACK跨越将会直接重传）
        nc: 1               # 是否关闭流控，默认是0代表不关闭，1代表关闭
    rTimeout: 10s
    sTimeout: 5s
    sBufferSize: 10

web:
    addr: 0.0.0.0:30000
    rTimeout: 10s
    sTimeout: 5s
    sBufferSize: 10

http:
    addr: 0.0.0.0:40000
    rTimeout: 10s
    sTimeout: 5s

grpc:
    addr: 0.0.0.0:50000

mysql:
    dsn: mmog:mmog@tcp(192.168.4.14:3306)/boomboat?charset=utf8mb4&parseTime=true&loc=Local
    slowThreshold: 100ms    # 慢日志阈值

mongo:
    uri: mongodb://root:mmog@192.168.4.14:27017
    socketTimeout: 3s       # 读写超时

redis:
    addr: 192.168.4.14:6379
    password: "123456"

nsq:
    addr: 192.168.4.60:4150
    lookupAddr: 192.168.4.60:4161

etcd:
    addr: 127.0.0.1:2379
    timeout: 3s
    keepalive: 15s          # 键的过期时间
    update: 10s             # 刷新间隔

debug: true
