zone: $ZONE                 # 地区索引

group: $GROUP               # 服务组

index: $INDEX               # 服务索引

log:
    level: 6                # 日志级别, 0:panic, 1:fatal, 2:error, 3:warn, 4:info, 5:debug, 6:trace
    maxSize: 10             # 文件容量(M)
    # maxBackup: 10           # 最大日志文件数
    maxAge: 30              # 日志文件过期删除天数
    compress: false         # 压缩

tcp:
    addr: $TCP
    noDelay: false          # 延迟发送
    rTimeout: 5s            # 读超时
    sTimeout: 5s            # 写超时
    sBufferSize: 10         # 发包通道缓冲区大小

kcp:
    addr: $KCP
    dataShards: 1           # 发包分片数
    parityShards: 0         # 冗余分片数
    noDelay:
        interval: 10ms      # 协议内部工作的 interval，比如 10ms或者 20ms
        resend: 2           # 快速重传模式，默认0关闭（设置为x, x次ACK跨越将会直接重传）
        nc: 1               # 是否关闭流控，默认是0代表不关闭，1代表关闭
    rTimeout: 5s
    sTimeout: 5s
    sBufferSize: 10

web:
    addr: $WEB
    rTimeout: 5s
    sTimeout: 5s
    sBufferSize: 10

http:
    addr: $HTTP
    rTimeout: 5s
    sTimeout: 5s

grpc:
    addr: $GRPC
    timeout: 5s             # 请求超时

mysql:
    dsn: "mmog:mmog@tcp(192.168.4.14:3306)/boomboat?charset=utf8mb4&parseTime=true&loc=Local"
    slowThreshold: 100ms    # 慢日志阈值
    rTimeout: 5s
    sTimeout: 5s

mongo:
    uri: "mongodb://root:mmog@192.168.4.14:27017"
    db: "test"
    socketTimeout: 5s       # 读写超时

redis:
    addr: "192.168.4.14:6379"
    password: "123456"

nsq:
    addr: "192.168.4.60:4150"
    lookupAddr: "192.168.4.60:4161"

etcd:
    addr: "127.0.0.1:2379"
    timeout: 5s
    keepalive: 15s          # 键的过期时间
    update: 10s             # 刷新间隔

rsa:
    privateKey: "-----BEGIN -----\nMIIEpAIBAAKCAQEAvs7JYzTLTMZ9BhJPDj3cSTz/3Gsm13ud21DBN3qCb1xHh7rf5rK5h2U+PyCixCPDToOVpWarhttsxl4iK/JqdA25nAKE+ye5DXdUru1Y/Q/adHt8ySLWrXg1OHJa/lV6lO/q5x/4eLvk2PZKaZca32Q4SJyvqL+ngkNQ4JURVazImevro55726hKhpOFYYPFvjKbt74FPSCw2znJAYM7ffC54crlLvtmWcpOXi+myDRFPdweg73qR6uQPZqswCFZZ5SsJAim1Ia9kd7bQzc5F7+Ux9V8hFGPydNUclN+zPeX94iYiGCSj5exyykHYV84BAmTQWb9Ik0ydWlA7qivkQIDAQABAoIBAQCSlrFXWx75C+DPQk+kBFhxl8CF6Xg8wgajkGXwplkBDucRWrtbNGGeqGRrATqq70LD1gmoubj7cSYfPACKvMGWCVlYhwL9JSZhNxVDEqt0N7LAHILgz7gYKyrQA+LuVGNJewx/pisxLkEBgi3m8yS9DPTErEOzpBIf3HGNKFjZ9QFuFy3Hl3y8OjkIMjx8iDsZkQs/gAoQm6sC7tYqgXlvoX3DO7I9rXjTtif4tKERl3KT+uxPNNqb9xKP1gSWWMvk3f/jlYh7uQEn5cPcNAxd32b1W9T8w2NUmzfc5O7+h6sUXqlgZFnHcTFoGkn1eiiDOIPudUd01SGxXjDycx4BAoGBAOePL/QTdVaEMdWCwXiSJgOaTcO2HGkl1jgwvB+0/a4tRzNArJHHdyivrBHwwwWQVPhuFNhbb9TiP30yORlYriXS2kClHNECT01gN/R+3BCClJU0rHYLwAWaLPB0foaiOcOD/ipzjZMBpfONDc+4jyXffrNMj7Szy+2iL4n/CRzxAoGBANLyemClV2h9OHM+TmdM28UHfGyT/MmRkdRNEaAJzKtalRwN6hr//1WUxLHA0o9hc2VNMgrOJ+PBzJX8fu/K+jL3qxDgbgiwvNdWvSCG91dzvQ0/kR+v5r2OElUVSvnzAw1ptBqb0cBua6Ug8r1EK10BUR0wdfncM0URDb39dTyhAoGAZ711nWLOUdldvisbZFoNn9WUe1buOYlTBM+IqKfccxkj6elSpuj3EIpLi6oSpT55YudmfVvRqU1HZl6GyD07oARr9URDubvQLXkq+GWRT/BAguwbS7ON7rSY5405VjX9rQNIblpglfjKEWgjROmJcE1FpSxqwWk/tpHPvII+4fECgYAznalcJJjytFEvwbslg6Ty3RYQ61UbbUclj4YUhtFRzGRX7P+vg5xSsIhAhlH/S3UVAIKSKkeQb0dEG/hjbGM0PW3aP1AtSDGs70hvwRaci3Fi4H7+Jehr0Wui7gbeihvhGFA9goscbuhgC2PZ8+g4Za4XWlhDvyG8cKPQLUiWgQKBgQDbZ2TVpbOPEX8f99AvkjdMJxdhWPSGTWd8s7tczcPe+LDGdn/mGl+TMkVxfLvB9irH4V28jM0uChiQQqQzF+MwGr8nyf5AnxYfLF/wwXgDLs913Fw89lgGaWssgUcTnFf0GhyrWFI1fGOPzJ9QglNiUQ4w/Psp2F4A3N2f+mKI1g==\n-----END -----"
    publicKey: "-----BEGIN -----\nMIIBCgKCAQEAvs7JYzTLTMZ9BhJPDj3cSTz/3Gsm13ud21DBN3qCb1xHh7rf5rK5h2U+PyCixCPDToOVpWarhttsxl4iK/JqdA25nAKE+ye5DXdUru1Y/Q/adHt8ySLWrXg1OHJa/lV6lO/q5x/4eLvk2PZKaZca32Q4SJyvqL+ngkNQ4JURVazImevro55726hKhpOFYYPFvjKbt74FPSCw2znJAYM7ffC54crlLvtmWcpOXi+myDRFPdweg73qR6uQPZqswCFZZ5SsJAim1Ia9kd7bQzc5F7+Ux9V8hFGPydNUclN+zPeX94iYiGCSj5exyykHYV84BAmTQWb9Ik0ydWlA7qivkQIDAQAB\n-----END -----"

debug: false
